### ISSUE TITLE
[BUG] Highlights feature breaks/overrides the vanilla highlights w/ no option to turn off

### ISSUE THREAD

**Issue by lmojzis** [SevenTV/Extension#541] opened 2023-04-25 01:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome, Firefox

### Current Behavior

The highlights feature breaks/overrides the vanilla highlights w/ no option to turn off.

### Expected Behavior

I expect to be able to disable handling of the highlights by 7TV as my friends and I are just used to the way Twitch handles highlights.

### Steps To Reproduce

Install the extension. Have your highlight settings overridden w/ no option to toggle.

**Comment by Batyodie** [comment] 2023-05-08 08:59
@lmojzis  Hello. Could you describe in more detail what the problem is. I didn't really understand.

I tried using "/w nickname" in chat with and without extension. Didn't see the difference. I turned everything on in the Highlights settings section, again I didn’t see any strange behavior.

**Comment by lmojzis** [comment] 2023-05-08 09:50
There is nothing related to whispers. Whede did that one come from?
This ticket is about the highlighting being bypassable.
ie. I have my own extension that does highlighting or I just prefer the vanilla behavior. But alas, 7TV extension force overrides it.

**Comment by Batyodie** [comment] 2023-05-08 14:27
@lmojzis it's just that you mentioned "/w" in the issue, I thought it was about her.

Which setting exactly breaks the behavior. You can also take a screenshot of what it looks like for you.

**Comment by lmojzis** [comment] 2023-05-08 14:53
I did not. I used w/ which is shorthand for with, much like w/o is without and w/e means whatever.

**Comment by Awakened-Redstone** [comment] 2023-05-10 16:12
The twitch highlights doesn't show with 7TV present, completely replacing the chat system can bring quite some parity issues with the original chat
![image](https://github.com/SevenTV/Extension/assets/40528665/e0495763-a641-48ee-9ab8-8b679d603948)
![image](https://github.com/SevenTV/Extension/assets/40528665/bbaeeb34-6ab0-466f-b9f9-39395b029b3f)

**Comment by AnatoleAM** [comment] 2023-05-10 16:33
@Awakened-Redstone,

this is not the place to argue about the extension's existence or your qualms with our handling of chat :slightly_smiling_face: support for the special twitch moderator highlights is desired as expressed in #501 and this very issue.

**Comment by lmojzis** [comment] 2023-05-19 21:49
I have no idea why you renamed the issue to something I am not reporting. I did not mention anything even remotely related to moderator highlights. All the original issue is asking for is a way to turn off 7TV highlight handling, much like BTTV and FFZ have the options to NOT touch chat messages. 7TV becomes overreaching and overriding everything in this regard. All I want 7TV for is to use specific 7TV features, not entirely replace the way I interact with chat. This issue snowballed some other reports that are unrelated. Please open separate issue for moderator highlights amends as this issue is not that.

**Comment by AnatoleAM** [comment] 2023-05-20 01:40
There is no "turn off 7TV handling", it's not possible, and would need to be separately implemented. Your issue was renamed as it is a feature request. I will close this issue as it is now invalid.

**Closed by AnatoleAM** 2023-05-20 01:40 UTC
Labels: enhancement
