### ISSUE TITLE
[Bug] Tab-complete for 7tv emotes breaks after being timed out in a chat

### ISSUE THREAD

**Issue by zuned11** [SevenTV/Extension#185] opened 2021-11-24 02:36 UTC
After being timed out, tab-complete for 7TV emotes (only 7tv) breaks and stops working. Fixes itself upon refresh.

This is on 2.0.2.

**Comment by Excellify** [comment] 2021-11-24 02:43
Duplicate of #165

**Closed** 2023-03-15 11:17 UTC
Labels: bug
