### ISSUE TITLE
[BUG] Clicking the "Emote Menu" doesn't close it after being opened

### ISSUE THREAD

**Issue by orientalsniper** [SevenTV/Extension#572] opened 2023-05-08 21:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

When I click the emote menu, it will display the emotes, however if I click it again, the emote menu won't close. This is not consistent with the other buttons next to it, "chat settings" button, "native twitch emotes" button.

### Expected Behavior

If I click the emotes menu after being opened, it should just close.

### Steps To Reproduce

1) Click emotes menu button at the bottom
2) The emotes menu should be displaying
3) Click emotes menu button again, **it won't close it**.

**Comment by AnatoleAM** [comment] 2023-05-08 21:55
Duplicate of #396

**Closed by AnatoleAM** 2023-05-08 21:55 UTC
Labels: bug
