### ISSUE TITLE
extension disables scrolling on twitch category pages

### ISSUE THREAD

**Issue by glitchered** [SevenTV/Extension#977] opened 2023-12-19 23:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

chrome latest uptodate

when loading any category page scrolling is broken. when changing to a different sort order it's working briefly. breaks again after a couple of pages down and moves back to the top and stop working again.

### Expected Behavior

working scrolling

### Steps To Reproduce

load any category page. try to scroll. if broken, change the sort order. try to scroll. if working at this point scroll down some amount and watch it break again.

**Comment by MatinAniss** [comment] 2023-12-21 02:20
Duplicate of #635

**Closed** 2023-12-21 02:21 UTC
Labels: bug

**Comment by glitchered** [comment] 2023-12-25 14:59
duplicate from may 25? damn is this bug old and still not fixed. tsk
