### ISSUE TITLE
[Bug] Random heart emotes shown

### ISSUE THREAD

**Issue by zetta** [SevenTV/Extension#228] opened 2022-03-03 02:50 UTC
**Describe the bug**
For instance when i read messages containing normal emotes 7tv app will show a random emote (most of the time is the same heart)

However the message doesn't contain anything special, only spaces. 

**To Reproduce**
1. Go to any channel
2. Click on the message textarea and type  a message containing emotes
3. See the bug

**Expected behavior**
It should not show unrequired emotes

**Screenshots**

![image](https://user-images.githubusercontent.com/204105/156486591-7a5a5c0d-beed-494c-b306-fd1321247da8.png)

![image](https://user-images.githubusercontent.com/204105/156486609-14633aff-8176-44d7-82d2-1f9da3b2a910.png)

**Version:**
2.1.4

**Comment by Cryptizism** [comment] 2022-03-06 00:04
I can't seem to replicate this issue, can you provide me with the following:
- What browser you are on?
- Whether or not you have any other extensions and if this occurs when you turn those other extensions off and have 7TV on?
- If you have other extensions, what do you have?
- If you can right-click and inspect element the heart; can you screenshot the style and the element?

**Comment by zetta** [comment] 2022-03-06 08:46
I can't seem to replicate this issue, can you provide me with the following:

- What browser you are on?
**Google Chrome Version 99.0.4844.51 (Official Build) (arm64)**

-  Whether or not you have any other extensions and if this occurs when you turn those other extensions off and have 7TV on?
**I also have BTTV Extension, the issue happen if BTTV extension is disabled.**
- If you have other extensions, what do you have?
 **Only BTTV Extension that works directly over twitch**
- If you can right-click and inspect element the heart; can you screenshot the style and the element?
  **Have you release a new version of the extension? today I can't replicate it anymore. (I just entered to twitch and found out that even the padding between emotes is quite different (no more padding between emotes)**
   
<img width="330" alt="image" src="https://user-images.githubusercontent.com/204105/156915591-9250108f-a4fa-4e15-9b3b-25d0306d981b.png">

**Comment by Cryptizism** [comment] 2022-03-06 14:31
> Have you release a new version of the extension? today I can't replicate it anymore. (I just entered to twitch and found out that even the padding between emotes is quite different (no more padding between emotes)

There has not been an update since the creation of this issue. Padding works completely fine for me, I know that FFZ has an option to disable padding but you said you only had 7TV & BTTV. Padding works completely fine for me. 7TV, AFAIK, has no option to change the padding plus there have been no recent updates to cause this issue. It also seems that BTTV also does not have this feature. Maybe having a look at the style and seeing what class has the 0 padding will help.

**Comment by zetta** [comment] 2022-03-07 00:38
I just saw it again.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/204105/156949604-ec7d4412-902d-42f7-b302-39d5a54102a7.png">

```html
<span class="seventv-message-context" style="position: relative;">
    <span class="seventv-text-fragment" style="word-break: break-word;">
        el exception ya no es TPM?
    </span>
    <span class="seventv-emote">
        <span style="min-width: 19.5px; min-height: 19.5px;">
            <img alt="  " class="chat-image chat-line__message--emote" src="https://twemoji.maxcdn.com/v/13.1.0/72x72/2764.png" srcset="https://twemoji.maxcdn.com/v/13.1.0/72x72/2764.png 1x, https://twemoji.maxcdn.com/v/13.1.0/72x72/2764.png 2x, https://twemoji.maxcdn.com/v/13.1.0/72x72/2764.png 4x">
        </span>
    </span>
    <span class="seventv-emote twitch-emote">
        <span style="min-width: 28px; min-height: 28px;">
            <img alt=" :p " class="chat-image chat-line__message--emote" src="https://static-cdn.jtvnw.net/emoticons/v2/12/default/dark/1.0" srcset="https://static-cdn.jtvnw.net/emoticons/v2/12/default/dark/1.0 1x, https://static-cdn.jtvnw.net/emoticons/v2/12/default/dark/2.0 2x, https://static-cdn.jtvnw.net/emoticons/v2/12/default/dark/3.0 4x">
        </span>
    </span>
</span>
```

**Comment by zetta** [comment] 2022-03-07 00:41
This is how it look when I try to spam only one emote 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/204105/156949882-aaabddd2-74b2-4815-b211-429303fd42af.png">

**Comment by zetta** [comment] 2022-03-10 04:03
Today is showing ⭐ 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/204105/157586172-9a48870e-a0aa-4619-b287-811b00f16a02.png">

This bug is really annoying, although quite curious

**Comment by AnatoleAM** [comment] 2022-03-10 04:09
Does this ever last more than a few seconds while loading a page? These are very obviously emojis, and **not** "emotes". I have not been capable of reproducing this issue.

**Comment by zetta** [comment] 2022-03-11 08:17
It does last even for hours, then sudenly they dissapear for a while and the glitch comes back. I have no clue what's going on

**Comment by Cryptizism** [comment] 2022-03-25 22:48
Seems to be an increasingly common issue (each image links to the message on the discord)
[![image](https://user-images.githubusercontent.com/60571306/160210923-993ae541-ea30-40a7-9d80-11ad513454fe.png)](https://discord.com/channels/817075418054000661/817127396938874890/956303309101236235)

Some additional info that might help:

BTTV, (FFZ?) AND 7TV Enabled:
[![image](https://user-images.githubusercontent.com/60571306/160211074-42a76a99-0841-411d-b92d-4a308c2f41f5.png)](https://discord.com/channels/817075418054000661/938903939649261598/956179745010249768)
(FFZ?) AND 7TV Enabled:
[![image](https://user-images.githubusercontent.com/60571306/160211098-d61c0241-0528-4909-a229-14dccea9cf79.png)](https://discord.com/channels/817075418054000661/938903939649261598/956198757106581525)

**Comment by AnatoleAM** [comment] 2022-03-25 22:52
Still unable to reproduce

**Comment by thenolite** [comment] 2022-03-30 11:38
Im also having this issue, I use windows 10 and am running Opera GX browser. I joined a chat and send a message with a sub emote from a different channel and it had blush emojis around it. When I asked about it, I was told it was just me and the streamer told me its  a 7tv bug he gets all of the time with heart emotes (like seen above) here are some photos 
![image](https://user-images.githubusercontent.com/102666970/160826129-cc5f30cf-d62e-41f1-932c-5c447cc5491c.png)
![image](https://user-images.githubusercontent.com/102666970/160826157-a0a73cb4-b6e2-43f2-87e4-a9fe054e931e.png)

**Comment by thenolite** [comment] 2022-03-30 11:39
I never told them the exact blush emoji, so im fairly certain all of the blushes typed were not intentional

**Comment by AnatoleAM** [comment] 2022-04-15 22:39
This issue has received a tentative fix. It is believed to be fixed in version 2.2.0, but cannot be confirmed due to the lack of reproducibility. Please feel free to re-open this issue if it's confirmed to still occur. (Ensure that you have received the update before reporting)

**Comment by zetta** [comment] 2022-04-18 03:58
Thanks @AnatoleAM , will check after the update for now after a quick view it seems it was fixed. I've also updated chrome recently also.

**Comment by zetta** [comment] 2022-04-18 04:16
Thanks @AnatoleAM it seems fixed now, although now it seems it created a new issue but have nothing to do with the emotes. thanks again.

**Comment by recursiveGecko** [comment] 2022-04-18 21:57
> Please feel free to re-open this issue if it's confirmed to still occur. (Ensure that you have received the update before reporting)

Unfortunately it doesn't seem like it's fixed.

![Screenshot 2022-04-18 235447](https://user-images.githubusercontent.com/1461520/163883972-180168b2-a43e-4165-93d7-a2381f6f4792.png)

![Screenshot 2022-04-18 235503](https://user-images.githubusercontent.com/1461520/163883982-6d7e821e-1336-4053-8eca-21523947c2a7.png)

**Comment by AnatoleAM** [comment] 2022-04-18 22:07
Odd, well at this time I've got no further clues on what would cause this. I have not been able to reproduce this issue a single time. I'll re-open and leave it to any contributors if they're experiencing this and wish to try fixing it.

**Comment by recursiveGecko** [comment] 2022-04-18 23:50
I'm not familiar with the codebase but if you can point me in the right direction I'm happy to take a look and try to help out with any debugging steps when it comes up again.

**Comment by AnatoleAM** [comment] 2022-04-19 20:33
> I'm not familiar with the codebase but if you can point me in the right direction I'm happy to take a look and try to help out with any debugging steps when it comes up again.

My best guess is it's caused by the `twemoji` package used to render emojis and the source of the issue *may* be [somewhere around here](https://github.com/SevenTV/SevenTV/blob/abadbbc6d4752eed67ee114e8e6287c1856977f2/src/Sites/twitch.tv/Components/MessageRenderer.tsx#L48). Perhaps the best thing to do at this point would be to completely change how emojis are rendered.

**Comment by Cryptizism** [comment] 2022-05-03 18:26
> My best guess is it's caused by the `twemoji` package used to render emojis and the source of the issue _may_ be [somewhere around here](https://github.com/SevenTV/SevenTV/blob/abadbbc6d4752eed67ee114e8e6287c1856977f2/src/Sites/twitch.tv/Components/MessageRenderer.tsx#L48). Perhaps the best thing to do at this point would be to completely change how emojis are rendered.

In those lines I see that the emojis are given a class of `seventv-emoji` and it does so when I post an emoji in a chat. However, I see that in https://github.com/SevenTV/SevenTV/issues/228#issuecomment-1060079448 there is no mention of the `seventv-emoji` in the inspect element just `seventv-emote`. I don't know what this could mean but I think it could be a start to a new lead @AnatoleAM

**Comment by GBRL-Web** [comment] 2022-05-24 09:27
![image](https://user-images.githubusercontent.com/68778251/169994232-c92999c3-6903-482f-9718-4c29c85b7702.png)

I've BTTV disabled too.
Firefox 100.0.2 (64-bit) [It did it on older versions too]
It has done it for around 20 minutes, I didn't refresh page and it seems that it has gone away by itself.
Earliest occurrence that I can recall was about 1-2 years ago. In this period it happened to me about 5-10 times max so it's not a daily thing [Long live inconsistency in bugs] and it went away by itself.

This was inside the 'seventv-emote' span too:

`<span style="min-width: 19.5px; min-height: 19.5px;">
<img alt="  " class="chat-image chat-line__message--emote" src="https://twemoji.maxcdn.com/v/14.0.2/72x72/2764.png" srcset="https://twemoji.maxcdn.com/v/14.0.2/72x72/2764.png 1x, https://twemoji.maxcdn.com/v/14.0.2/72x72/2764.png 2x, https://twemoji.maxcdn.com/v/14.0.2/72x72/2764.png 4x"></span>`

For me it was constantly the big hearts, whenever it happened. [It's a once every few tens of times.] It does replace the space in between words but I wasn't paying too much attention if it does it only on lines where emotes are called or before/after. 
There might be a pattern.
If it happens again and I find anything new, I will post it here.

**Comment by MacheteFFS** [comment] 2022-06-12 08:04
Having the same issue. 

![image](https://user-images.githubusercontent.com/107343859/173223408-25e65937-082f-4d03-933a-0266df77d218.png)

**Comment by dakillerclown87** [comment] 2022-06-22 04:52
I also have this issue but
and it happens when i @ someone and then after any emote that I type out, but from the looks of it it only happens on my end... I think, I was watching a stream that had the chat on stream and it doesn't appear on there side, unless they need to have 7tv installed.

but other than that this happens to me sometimes, which does get annoying. and I only have 7tv and bttv on for twitch.

**Comment by rGhede** [comment] 2022-07-07 00:28
I'm also having this issue, but it's not when I type the emotes, it's during raids, it seems to render a random heart emote before and after other emotes.
![image](https://user-images.githubusercontent.com/66904466/177664057-6277030b-5ef5-44cf-8370-8f734a8f209f.png)

**Comment by fabiosciacallo** [comment] 2022-07-13 17:07
I'm having the same issue, every time with a different emoji. Refreshing the page fixes so its not a big deal.

**Comment by Sad-theFaceless** [comment] 2022-09-30 23:41
Same issue, as already said regreshing the page fixes it.

**Comment by watertthewet** [comment] 2022-10-17 01:11
I have the same issue, but only with one channel: https://www.twitch.tv/ellyen
but instead of hearts, it's giant thumbsdown emotes 
![image](https://user-images.githubusercontent.com/25522732/196069126-86540f91-47b1-4e47-afbe-cb93569c5c5c.png)

I'm running Firefox.

**Comment by MysterTwitch** [comment] 2022-11-17 19:13
Same issue here

    What browser you are on?
-Firefox
    Whether or not you have any other extensions and if this occurs when you turn those other extensions off and have 7TV on?
-Several, but even after uninstalling them all and running with just 7TV it persists.

    If you have other extensions, what do you have?
AdBlocker Ultimate
BetterTTV
Firefox Translations
Ghostery - Privacy Ad Blocker
Private Internet Access
Zoom Scheduler
    If you can right-click and inspect element the heart; can you screenshot the style and the element?
Same as others, just says Global Emote and ?

**Comment by Bazeloth** [comment] 2022-11-19 16:31
![image](https://user-images.githubusercontent.com/19928782/202861357-a7cbd88f-9be7-4062-b9d9-3fb5a91f81da.png)
![image](https://user-images.githubusercontent.com/19928782/202861366-0a7ef70a-ec43-4d62-95bd-f8834140dbd2.png)
![image](https://user-images.githubusercontent.com/19928782/202861377-e755db2a-2cda-4c49-aa44-5f3e6bb08f55.png)
![image](https://user-images.githubusercontent.com/19928782/202861399-9b17ec31-ca74-4554-bbe3-b71ca57d830e.png)

Chrome browser.

**Closed** 2023-03-15 11:17 UTC
Labels: bug
