### ISSUE TITLE
[BUG] Twitch - Can't scroll through streams with 7TV enabled

### ISSUE THREAD

**Issue by FluxVII** [SevenTV/Extension#777] opened 2023-07-12 08:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome

### Current Behavior

Whenever I'm scrolling through streams in Just Chatting for example, I can scroll all the way to the bottom no issues. 

As soon as I open another stream in a new tab or window, the page automatically scrolls all the way back to the top and freezes there. I can switch from recommend channels to high to low which temporarily fixes it for about 10 seconds, then that also scrolls to the top.

Refreshing the page does nothing but if I close any streams that I have open and refresh then it behaves as normal.

I have tried disabling every extension but 7TV to see if maybe something is conflicting but it still does it even when its the only extension enabled. 

### Expected Behavior

Being able to scroll 

### Steps To Reproduce

Click on Just Chatting.

Scroll down a bit.

Open a stream in a new tab (don't even have to click on the new tab).

Few seconds after that new tab loads it scrolls back to the top and is locked there.

**Comment by egret85** [comment] 2023-07-13 16:20
I have this issue as well.  Seems like the same issue reported in #635, but that issue was closed, so not sure anyone is looking at it anymore. There is good info there that describes the issue as well as a linked YouTube video showing the issue.

**Comment by aj479** [comment] 2023-07-15 03:19
I'm still having the same issue also and I even went around switch browsers three times and it still happens, it's definitely the extension causing the problem. You can fix it by just disabling the extension altogether . It seems this problem occurs with a small amount of users.

Example : https://youtu.be/O6cqk3QiRXs

**Comment by jaaneh** [comment] 2023-07-15 22:10
Also experiencing this issue. Only happens with stream previews disabled. 

Until this is fixed I've manually allowed scroll on overflow and hid the default scrollbar it creates. Added this using Stylus extension.
```css
.switcher-hopper {
    overflow-y: scroll !important;
}
::-webkit-scrollbar {
  width: 0;
}
```

**Comment by MatinAniss** [comment] 2023-07-15 23:05
These elements seem to get deleted causing the scroll bar to disappear.
![image](https://github.com/SevenTV/Extension/assets/76515905/2ac098d7-a6f0-4417-b328-7d1b8735e29e)

**Comment by AnatoleAM** [comment] 2023-07-16 05:26
Duplicate of #635

**Closed by AnatoleAM** 2023-07-16 05:26 UTC
Labels: bug
