### ISSUE TITLE
[BUG] Unable to Link Youtube Channel with 7tv

### ISSUE THREAD

**Issue by Kevv-J** [SevenTV/Extension#533] opened 2023-04-22 20:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Firefox

### Current Behavior

Clicking on Link Account on Users page https://7tv.app/users/<user-id> takes me to https://old.7tv.app/link-youtube
Here on clicking on Sign in with Twitch It gives [404 Not Found error](https://7tv.io/v3/auth/twitch?old=true) with details. "The API endpoint requested does not exist"
![image](https://user-images.githubusercontent.com/38836436/233805842-b0e8b27c-59b6-45fc-a83a-688ddb1a662c.png)

Not able to connect my Youtube Account with 7tv for enabling emotes

### Expected Behavior

I should be able to Connect my Youtube account with 7tv to enable 7tv emotes on my youtube stream

### Steps To Reproduce

1. Go to User page
2. Click on Link Accounts Youtube
3. Select Sign-In with Twitch to connect Youtube Account.
4. API Error shows up

**Comment by AnatoleAM** [comment] 2023-04-27 10:56
Duplicate of #456

**Closed by AnatoleAM** 2023-04-27 10:56 UTC
Labels: bug

**Comment by Kevv-J** [comment] 2023-04-27 11:16
Please remove the mention of connecting Youtube channel on 7tv app if you do not plan to have this feature anymore in the latest version of 7tv. Very confusing for users which eventually leads to disappointment that this feature has been discontinued.
