### ISSUE TITLE
[Request] Option to sort emotes 

### ISSUE THREAD

**Issue by ItsJugg** [SevenTV/Extension#511] opened 2023-04-14 23:13 UTC
Can you add an option to sort the emotes in the emote menu by most recently added? It was like that before the 3.0 update but not anymore.

**Comment by MatinAniss** [comment] 2023-04-14 23:55
Related issue #398

**Comment by AnatoleAM** [comment] 2023-05-12 19:07
Duplicate of #398

**Closed** 2023-05-12 19:07 UTC
Labels: enhancement
