### ISSUE TITLE
[Bug] Opening a message thread/replies only shows one reply instead of the whole thread

### ISSUE THREAD

**Issue by neverknowsless** [SevenTV/Extension#424] opened 2023-03-29 08:39 UTC
When opening a message thread/reply it only shows one reply instead of the whole thread. Replying to threads is more difficult now because I don't know who's message I'll be replying to. Turning off 7TV and using stock Twitch or BTTV makes threads work regular again.

**Comment by AnatoleAM** [comment] 2023-03-30 03:07
Duplicate of #386, fixed in v3.0.2 via #422

**Closed by AnatoleAM** 2023-03-30 03:07 UTC
