### ISSUE TITLE
[BUG] 7TV chat overlay and 7TV emotes not appearing

### ISSUE THREAD

**Issue by Inglonias** [SevenTV/Extension#1003] opened 2024-02-14 14:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Chrome, Firefox

### Current Behavior

![image](https://github.com/SevenTV/Extension/assets/2125926/01ac77ce-59d9-4eb7-a164-98c97a487d9a)
This screenshot was taken in Firefox, but the same behavior is occurring on this computer in Chrome as well.

### Expected Behavior

I expect to see 7TV emotes and the 7TV emote menu.

### Steps To Reproduce

Unknown. This just started happening on my desktop yesterday. I'm not seeing any errors in the console.

I have reinstalled Firefox, used a separate browser, tried both the stable and nightly releases. I don't know what else to do to debug this situation, and I don't know if this is actually a bug or not.

**Comment by treuks** [comment] 2024-02-14 15:03
The issue is caused due to a twitch experiment, which updates the React version to a newer one, and completely breaks all twitch extensions which rely on hooking.

**Comment by Inglonias** [comment] 2024-02-14 15:03
Just tested this on my laptop as well - same behavior.

**Comment by treuks** [comment] 2024-02-14 15:06
To fix this (temporarily), you can delete the twitch cookie and refresh the page:
Developer Tools (F12) -> Application -> Cookies -> right click on twitch.tv -> clear

![image](https://github.com/SevenTV/Extension/assets/18615981/9306dbf1-cee0-4e9b-97f8-3ef6bd6245b2)

**Comment by Inglonias** [comment] 2024-02-14 15:11
This works, but I'd love to know how you figured this out.

**Comment by TroyKomodo** [comment] 2024-02-17 07:11
fixed in #1004

**Closed by TroyKomodo** 2024-02-17 07:11 UTC
Labels: bug
