### ISSUE TITLE
[Question] default chat design

### ISSUE THREAD

**Issue by Catta1997** [SevenTV/Extension#564] opened 2023-05-02 17:09 UTC
As a moderator I like more the default design (like default "VIP" / first message etc )  box . there is a way to do it? Like only emote and nothing else

**Comment by DanielFirpo** [comment] 2023-05-04 19:26
> As a moderator I like more the default design (like default "VIP" / first message etc ) box . there is a way to do it? Like only emote and nothing else

Almost every thing can be toggled off in the settings. Check the hightlight tab in settings, can toggle off first message/mention hightlights etc.

**Comment by DanielFirpo** [comment] 2023-05-04 21:03
hmm idk actually, probably not actually. I'm not a mod in any channels where its easy to test tho so idk for sure

**Comment by AnatoleAM** [comment] 2023-05-11 13:29
Duplicate of #541

**Closed by AnatoleAM** 2023-05-11 13:29 UTC

**Comment by AnatoleAM** [comment] 2023-05-11 18:46
Make a new feature request for that one then :slightly_smiling_face: please note there is no such thing as "default chat design", so you must phrase it as something to be implemented, as it's not possible to simply "revert" to the default design.
